routes/web.php
<?php

use Illuminate\Support\Facades\Hash;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});


Auth::routes();
Route::get('/coba','CobaController@coba');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/homesalary', 'HomeController@salary')->name('home');
Route::get('/homesalary/cetak_pdf', 'HomeController@cetak_pdf')->name('home');
Route::get('/homemaster', 'HomeController@master')->name('homepm');

Route::post('/home/change_password','Admin\UserController@changepassword');
Route::group(['prefix'=> 'client,', 'middleware' => ['auth']], function(){
    Route::resource('/','HomeController@index');
    //Route::get('coba/{id}','AdminController@show');
});
//tim
Route::post('/proyek/{id_proyek}','HomeController@cekstatus')->middleware('cek','auth');
//pm & client
Route::post('/master/{id_proyek}','HomeController@cekstatus')->middleware('cekmaster','auth');

Route::group(['prefix'=> 'pm', 'middleware' => ['pm','auth']], function(){
    Route::get('/{id_proyek}','PmController@index')->name('Pmhome');
    Route::get('/tasklist/{id_proyek}','TasklistController@index');
    Route::resource('Task','TasklistController');
    Route::get('/timeline/{id_proyek}','PmController@gant');
    Route::get('/tim/{id_proyek}','Pm\TimController@index');
    Route::resource('Tim','Pm\TimController');
    Route::get('/dokumen/{id_proyek}','Pm\DokumenController@index');
    Route::resource('Dokumen','Pm\DokumenController');
    Route::get('dokumen/{id_dokumen}/download', 'Pm\DokumenController@download')->name('dokumen.download');
    //Route::get('tim/{id}','AdminController@show');
});

//client
Route::group(['prefix'=> 'client', 'middleware' => ['client','auth']], function(){
    Route::get('/{id_proyek}','Client\ClientController@index')->name('Clienthome');
    Route::get('/tasklist/{id_proyek}','Client\TasklistController@index');
    Route::resource('ClientTask','Client\TasklistController');
    //Route::get('coba/{id}','AdminController@show');
});

Route::group(['prefix'=> 'tester', 'middleware' => ['tester','auth']], function(){
    Route::get('/{id_proyek}','Tester\TesterController@index')->name('Testerhome');
    Route::get('/tasklist/{id_proyek}','Tester\TasklistController@index');
    Route::resource('TesterTask','Tester\TasklistController');
    //Route::get('coba/{id}','AdminController@show');
});

Route::group(['prefix'=> 'programmer', 'middleware' => ['programmer','auth']], function(){
    Route::get('/{id_proyek}','Programmer\ProgrammerController@index')->name('Programmerhome');
    //tasklist
    Route::get('/tasklist/{id_proyek}','Programmer\TasklistController@index');
    Route::resource('ProgrammerTask','Programmer\TasklistController');

    //timeline
    Route::get('/timeline/{id_proyek}','Programmer\ProgrammerController@timeline')->name('Programmerhome');
    //dokumen
    Route::get('/dokumen/{id_proyek}','Programmer\DokumenController@index');
    Route::resource('PenulisDokumen','Programmer\DokumenController');
    Route::get('dokumen/{id_dokumen}/download', 'Programmer\DokumenController@download')->name('programmerdokumen.download');
    //Route::get('coba/{id}','AdminController@show');
});

Route::group(['prefix'=> 'analis', 'middleware' => ['analis','auth']], function(){
    Route::get('/{id_proyek}','Analis\AnalisController@index')->name('Analishome');
    //tasklist
    Route::get('/tasklist/{id_proyek}','Analis\TasklistController@index');
    Route::resource('AnalisTask','Analis\TasklistController');
    //timeline
    Route::get('/timeline/{id_proyek}','Analis\AnalisController@timeline');

    //myTask
    Route::get('/mytask/{id_proyek}','Analis\AnalisController@mytask');
    //myTask
    Route::PUT('/mytaskupdate/{id_task}','Analis\AnalisController@mytaskupdate');
    //dokumen
    Route::get('/dokumen/{id_proyek}','Analis\DokumenController@index');
    Route::resource('AnalisDokumen','Analis\DokumenController');
    Route::get('dokumen/{id_dokumen}/download', 'Analis\DokumenController@download')->name('analisdokumen.download');
    //Route::get('coba/{id}','AdminController@show');
});
Route::group(['prefix'=> 'admin', 'middleware' => ['admin','auth']], function(){
    Route::resource('/','AdminController');
    Route::resource('User','Admin\UserController');
    Route::resource('Proyek','Admin\ProyekController');
   
});

//auth
Route::get('auth/{provider}', 'AuthController@redirectToProvider');
Route::get('auth/{provider}/callback', 'AuthController@handleProviderCallback');

app/Http/Controllers/Analis/AnalisController.php
<?php

namespace App\Http\Controllers\Analis;
use Alert;
use App\Task;
use Auth;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AnalisController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($id_proyek)
    {
        $user = Auth::user()->name;
        Alert::info('Selamat Datang ' .$user,'Hello !');
        return view('analis.index',compact('id_proyek'));
    }

    public function mytask($id_proyek)
    {
        $user = Auth::user()->name;
        $mytasks = Task::where('id_proyek',$id_proyek)->where('id_analis','<>',NULL)->get();
        return view('analis.mytask',compact('mytasks','id_proyek'));
    }

    public function mytaskupdate($id_task)
    {
        $id_proyek = $request->get('id_proyek');
        $task = Task::find($id_task);
        $task->status_analis = $request->get('status_analis');

        Alert::success('Sukses','Selamat!');
        return back();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function timeline($id_proyek){
        $id_proyek = $id_proyek;
        return view('analis.timeline',compact('id_proyek'));
    }
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Analis/DokumenController.php
<?php

namespace App\Http\Controllers\Analis;

use Illuminate\Http\Request;
use App\Dokumen;
use App\Http\Controllers\Controller;
use Alert;
use Carbon\Carbon;

class DokumenController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($id)
    {
        $dokumens = Dokumen::where('id_proyek',$id)->get();
        $id_proyek=$id;
        if(count($dokumens) > 0){
        
        return view('analis.dokumen',compact('dokumens','id_proyek'));
        }else{
            
        Alert::error('Tidak ada data','Oopss !')->persistent("Close");
        return view('analis.dokumen',compact('dokumens','id_proyek'));
        }
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $tgl_upload= Carbon::now()->format('Y-m-d');

        $file = $request->file('file');
        $ext = $file->getClientOriginalExtension();
        $newName = rand(100000,1001238912).".".$ext;
        $file->move('uploads/file',$newName);

        $dokumen = new Dokumen;
        $dokumen->nama_dokumen = $request->get('nama_dokumen');
        $dokumen->id_proyek = $request->get('id_proyek');
        $dokumen->tgl_upload = $tgl_upload;
        $dokumen->file = $newName;
        $dokumen->save();

        Alert::success('Dokumen berhasil ditambahkan','Sukses !')->persistent("Close");
        return back();

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
        $dokumen = Dokumen::find($id);

        if($request->file('file') == "")
        {
            $dokumen->file = $dokumen->file;
        } 
        else
        {
            $file       = $request->file('file');
            $fileName   = $file->getClientOriginalName();
            $request->file('file')->move('uploads/file', $fileName);
            $dokumen->file = $fileName;
        }
        // $file = $request->file('file');
        // $ext = $file->getClientOriginalExtension();
        // $newName = $request->file.".".$ext;
        // $file->move('uploads/file',$newName);

        $dokumen->nama_dokumen = $request->get('text');
        
        $dokumen->save();

        Alert::success('Dokumen berhasil diubah','Sukses !')->persistent("Close");
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $dokumen = Dokumen::find($id);
        $dokumen->delete();

        Alert::success('Dokumen berhasil dihapus','Sukses !')->persistent("Close");
        return back();
    }
    public function download($id_dokumen)
    {
        //$model_file = Model::findOrFail($id_dokumen);
        $book = Dokumen::where('id_dokumen', $id_dokumen)->firstOrFail();
        $pathToFile = ('uploads/file/'.$book->file);
        $name=$book->nama_dokumen.'.docx';
        return response()->download($pathToFile,$name);
    }
}

app/Http/Controllers/Analis/TasklistController.php
<?php


namespace App\Http\Controllers\Analis;


use App\Http\Controllers\Controller;
use App\Task;
use App\Tim;
use Illuminate\Http\Request;
use Carbon\Carbon;
use App\Notif;
use Alert;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;

class TasklistController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($id)
    {
        $warning_date = Carbon::now()->addDays(7)->format('Y-m-d');
        // $users = DB::table('task')
        //     ->join('tim', 'tim.id_tim', '=', 'task.id_tim')
        //     ->join('users', 'tim.id_user', '=', 'users.id')
        //     ->where('task.finish_date','<',$warning_date)
        //     ->select('task.id as id_task','users.id as id_user','tim.id_tim','task.text','task.finish_date')
        //     ->get();
        //     dd($users);
        $tgl_sekarang= Carbon::now()->formatLocalized('%A, %d %B %Y');
        $warning_date = Carbon::now()->addDays(7)->format('Y-m-d');
        $notifikasi =Notif::where('id_user','=',Auth::user()->id);
        $id_proyek = $id;
        $tasks = Task::where('id_proyek','=',$id)->get();
      
        $programmers = Tim::where('id_proyek','=',$id)->where('jabatan','programmer')->get();
        if (count($tasks) <= 0){
            Alert::error('Tidak ada data','Oopss !');
            return view('analis.task',compact('tasks','id_proyek','programmers','warning_date','tgl_sekarang'));   
        }
        return view('analis.task',compact('tasks','id_proyek','programmers','warning_date','tgl_sekarang'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $start_date = $request->get('start_date');// pendefinisian tanggal awal
        $duration = $request->get('duration');
        $finish = date('Y-m-d', strtotime('+'.$duration.' days', strtotime($start_date))); 

        $task = New Task();
        $task->text = $request->get('text');
        $task->duration = $duration;
        $task->start_date = $start_date;
        $task->finish_date = $finish;  
        $task->id_proyek = $request->get('id_proyek');  
        $task->id_tim = $request->get('id_tim');
        $task->status = '';
        $task->status_deployprogrammer = '' ;
        $task->status_deploypm = '';
        $task->save();


        Alert::success('Data tasklist berhasil ditambahkan','Selamat !')->persistent("Close");
        return back();

    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request,$id)
    {
        $task=Task::find($id);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $analis_update = $request->get('status_analis');
        if($analis_update != NULL or $analis_update != ''){
            $task = Task::find($id);
            $task->status_analis = $request->get('status_analis');
            $task->save();
    
            Alert::success('Data tasklist berhasil diubah','Selamat !')->persistent("Close");;
            return back();
        }else{
        $start_date = $request->get('start_date');// pendefinisian tanggal awal
        $duration = $request->get('duration');
        $finish = date('Y-m-d', strtotime('+'.$duration.' days', strtotime($start_date))); 
        
        $task = Task::find($id);
        $task->text = $request->get('text');
        $task->duration = $duration;
        $task->start_date = $start_date; 
        $task->finish_date = $finish;
        $task->id_proyek = $request->get('id_proyek');  
        $task->id_tim = $request->get('id_tim');
        $task->save();

        Alert::success('Data tasklist berhasil diubah','Selamat !')->persistent("Close");;
        return back();
    }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $task = Task::find($id);
        $task->delete();

        Alert::success('Data tasklist berhasil dihapus','Selamat !')->persistent("Close");;
        return back();
    }
}

resources/views/analis/task.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 2 | Data Tables</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{{url('assets/bower_components/bootstrap/dist/css/bootstrap.min.css')}}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{url('assets/bower_components/font-awesome/css/font-awesome.min.css')}}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{{url('assets/bower_components/Ionicons/css/ionicons.min.css')}}">
  <!-- DataTables -->
  <link rel="stylesheet" href="{{url('assets/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{url('assets/dist/css/AdminLTE.min.css')}}">
   <!-- Select2 -->
   <link rel="stylesheet" href="{{url('assets/bower_components/select2/dist/css/select2.min.css')}}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{{url('assets/dist/css/skins/_all-skins.min.css')}}">
  
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  @include('admin.header')
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="{{url('assets/dist/img/user2-160x160.jpg')}}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>{{Auth::user()->name}}</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>

      <-- sidebar menu: : style can be found in sidebar.less -->
     <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MAIN NAVIGATION</li>
        <li class="">
          <a href="/analis/{{$id_proyek}}">
            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
          </a>   
        </li>

        <li class="">
          <a href="/analis/timeline/{{$id_proyek}}">
          
            <i class="fa fa-calendar"></i> <span>Timelines</span>
         
          </a>   
        </li>

        <li class="active">
          <a href="/analis/tasklist/{{$id_proyek}}">
            <i class="fa fa-tasks"></i> <span>Tasklist</span>
          </a>   
        </li>

        <li class="">
          <a href="/analis/dokumen/{{$id_proyek}}">
            <i class="fa fa-book"></i> <span>Dokumen</span>
          </a>   
        </li>

      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Data tim
        <small>Manajemen tim Karisma</small>
      </h1>
      <ol class="breadcrumb">
      <p>{{$tgl_sekarang}}</p>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
     
        <div class="col-xs-12">
          <!-- /.box -->
          <div class="box">
            <div class="box-header">
                <button class="btn btn-primary btn-flat" data-toggle="modal" data-target="#tambahdata">Tambah Data</button>
                <a class="btn btn-default btn-flat" href="/analis/mytask/{{$id_proyek}}">My Task</a>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Task</th>
                  <th>Remaining Time</th>
                  <th>Programmer</th>
                  <th>Harga</th>
                  <th>Status Test</th>
                  <!-- <th>S.Programmer</th>
                  <th>S.Pm</th> -->
                  <th>Aksi</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($tasks as $task)
                @if($task->finish_date < $warning_date)
                <tr style="background-color:yellow;">
                  <td>{{$task->text}}</td>
                  <td></td>
                  <td>{{$task->tim->karyawan->name}}</td>
                  <td>{{$task->harga}}</td>
                  <td>{{$task->status}}</td>
                  <!-- <td>{{$task->status_deployprogrammer}}</td>
                  <td>{{$task->status_deploypm}}</td> -->
                  <td>
                  <form class="delete" action="{{route('Task.destroy', $task->id)}} " method="post">
                  <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#{{$task->id}}">Edit</button>
                    
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger btn-sm" type="submit" onclick="return confirm('Anda yakin menghapus data ini?')">Delete</button>
                  </form>
                  </td>
                </tr>
                @else
                <tr>
                  <td>{{$task->text}}</td>
                  <td></td>
                  <td>{{$task->tim->karyawan->name}}</td>
                  <td>{{$task->harga}}</td>
                  <td>{{$task->status}}</td>
                  <!-- <td>{{$task->status_deployprogrammer}}</td>
                  <td>{{$task->status_deploypm}}</td> -->
                  <td>
                  <form class="delete" action="{{route('AnalisTask.destroy', $task->id)}} " method="post">
                  <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#{{$task->id}}">Edit</button>
                    
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger btn-sm" type="submit" onclick="return confirm('Anda yakin menghapus data ini?')">Delete</button>
                  </form>
                  </td>
                </tr>
                @endif
                @endforeach
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 2.4.0
    </div>
    <strong>Copyright &copy; 2014-2016 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights
    reserved.
  </footer>

<div id="tambahdata" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal tambah data content-->
  <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Tambah Task</h4>
      </div>
      <div class="modal-body">
        <form  method="POST" action="{{route('AnalisTask.store')}}">
          @csrf
              <div class="box-body">
                <div class="form-group">
                  <label>Task</label>
                  <input type="text" name="text" class="form-control" required>
                </div>

                <div class="form-group">
                  <label>Durasi</label>
                  <input type="number" name="duration" class="form-control" required>
                </div>
                
                <div class="form-group">
                  <label>Start Date</label>
                  <input type="date" name="start_date" class="form-control" required>
                </div>
                
                <div class="form-group">
                  <label>Programmer</label>
                  <select class="form-control" name="id_tim" required>
                  <option selected="selected">Pilih Programmer</option>
                  @foreach($programmers as $programer)
                    
                    <option value="{{$programer->id_tim}}">{{$programer->karyawan->name}}</option>
                  @endforeach
                  </select>
                </div>

                
                  <input type="hidden" name="id_proyek" value="{{$id_proyek}}">
                 

              </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button> 
              
        </form>
      </div>
    </div>

  </div>
</div>

<!-- Modal tambah edit content-->
@foreach($tasks as $task)
<div id="{{$task->id}}" class="modal fade" role="dialog">
  <div class="modal-dialog">

  <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Edit Task</h4>
      </div>
      <div class="modal-body">
        <form  method="POST" action="{{route('AnalisTask.update', $task->id)}}">
          @method('PATCH')
          @csrf
              <div class="box-body">
                
              <div class="form-group">
                  <label>Task</label>
                  <input type="text" name="text" value="{{$task->text}}" class="form-control" required>
                </div>

                <div class="form-group">
                  <label>Durasi</label>
                  <input type="number" name="duration" value="{{$task->duration}}" class="form-control" required>
                </div>
                
                <div class="form-group">
                  <label>Start Date</label>
                  <input type="date" name="start_date" value="{{$task->start_date}}" class="form-control" required>
                </div>
                
                <div class="form-group">
                  <label>Programmer</label>
                  <select class="form-control" name="id_tim" required>
                  @foreach($programmers as $programer)
                    <option value="{{$task->id_tim}}" selected="selected">{{$task->tim->karyawan->name}}</option>
                    <option value="{{$programer->id_tim}}">{{$programer->karyawan->name}}</option>
                  @endforeach
                  </select>
                </div>

                
                  <input type="hidden" name="id_proyek" value="{{$id_proyek}}">
                  
   
              </div>

         
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Simpan</button>
        </form>
      </div>
    </div>

  </div>
</div>
@endforeach




<!-- jQuery 3 -->
<script src="{{url('assets/bower_components/jquery/dist/jquery.min.js')}}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{url('assets/bower_components/bootstrap/dist/js/bootstrap.min.js')}}"></script>
<!-- DataTables -->
<script src="{{url('assets/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{url('assets/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
<!-- Slimscroll -->
<script src="{{url('assets/bower_components/jquery-slimscroll/jquery.slimscroll.min.js')}}"></script>
<!-- FastClick -->
<script src="{{url('assets/bower_components/fastclick/lib/fastclick.js')}}"></script>
<!-- Select2 -->
<script src="{{url('assets/bower_components/select2/dist/js/select2.full.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{url('assets/dist/js/adminlte.min.js')}}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{url('assets/dist/js/demo.js')}}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
@include('sweet::alert')
<!-- page script -->
<script>
  $(function () {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
</script>
<script>
  $(function () {
    //Initialize Select2 Elements
    $('.select2').select2()
  })
</script>
</body>
</html>